"""K.U.A. async job pipeline package.

IMPORTANT: Importing this package immediately installs the safe LogRecord
factory from :mod:`jobs.logging_util`. This guarantees that every LogRecord
created from this point on (including ones generated by third-party
libraries the worker imports later) carries safe default values for the
custom fields any formatter might reference (``job_id``, ``step_key``, …).

This is the first line of defense against
``ValueError: Formatting field not found in record: 'job_id'`` crashes
caused by a stale or misconfigured formatter anywhere in the process.
"""

from __future__ import annotations

# Side-effect import: installs the global LogRecord factory immediately.
from jobs.logging_util import _install_safe_log_record_factory  # noqa: F401

_install_safe_log_record_factory()
